config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "caravans#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "caravans#index"
  get "caravans/my_listings", to: "caravans#user_listings", as: :user_listings

  resources :caravans, only: [:index, :show, :new, :create, :update, :destroy, :edit] do
    resources :bookings, only: [:create]
  end

  resources :bookings, only: [:index, :show, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :caravan
  belongs_to :user

  validates :start_date, :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/caravan.rb
class Caravan < ApplicationRecord
  FUEL_TYPES = ["diesel", "petrol", "electricity"]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos, dependent: :destroy
  geocoded_by :location
  after_validation :geocode

  validates :model, presence: true, length: { minimum: 3 }
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :location, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :fuelType, presence: true, inclusion: { in: FUEL_TYPES }

  def unavailable_dates
    bookings.pluck(:start_date, :end_date).map do |range|
      { from: range[0], to: range[1] }
    end
  end
  
  include PgSearch::Model

  pg_search_scope :search_by_model_and_location,
    against: [ :model, :location ],
    associated_against: {
    user: [ :username, :email ]
    },
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo

  validates :username, presence: true, uniqueness: true
  has_many :bookings, dependent: :destroy
  has_many :caravans, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.where(user: current_user)
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.caravan = Caravan.find(params[:caravan_id])
    @booking.user = current_user
    if @booking.save
      redirect_to booking_path(@booking)
      flash[:notice] = "Your booking has been successful!"
    else
      render 'caravans/show', status: :unprocessable_entity
      flash[:alert] = "Booking unsuccesful"
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/caravans_controller.rb
class CaravansController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    @caravans = Caravan.all
    if params[:query].present?
      @caravans = Caravan.search_by_model_and_location(params[:query])
    else
      @caravans = Caravan.all
    end
    @markers = @caravans.map do |caravan|
      {
        lat: caravan.latitude,
        lng: caravan.longitude,
        info_window: render_to_string(partial: "info_window", locals: {caravan: caravan}),
        image_url: helpers.asset_url("logo.png")
      }
    end
  end

  def show
    @caravan = Caravan.find(params[:id])
    @booking = Booking.new
    @booking.user = current_user
    @booking.caravan = @caravan
  end

  def new
    @caravan = Caravan.new
  end

  def create
    @caravan = Caravan.new(caravan_params)
    @caravan.user = current_user
    if @caravan.save
      redirect_to caravan_path(@caravan)
      flash[:notice] = "Your listing has been created!"
    else
      render :new, status: :unprocessable_entity
      flash[:alert] = "Listing creation unsuccesful"
    end
  end

  def edit
    @caravan = Caravan.find(params[:id])
  end

  def update
    @caravan = Caravan.find(params[:id])
    if @caravan.update(caravan_params)
      redirect_to caravan_path(@caravan)
      flash[:notice] = "Your listing has been changed!"
    else
      render :edit, status: :unprocessable_entity
      flash[:alert] = "Couldn't change your listing"
    end
  end

  def destroy
    @caravan = Caravan.find(params[:id])
    @caravan.destroy
    redirect_to user_listings_path
    flash[:notice] = "Your listing has been deleted!"
  end

  def user_listings
    @caravans = Caravan.where(user: current_user)
  end

  private

  def caravan_params
    params.require(:caravan).permit(:model, :location, :price, :capacity, :year, :fuelType, :picture_url, :description, photos: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.photo.attach(params[:photo])
    if @user.update(user_params)
      flash[:notice] = "Your account information was succesfully updated"
      redirect_to caravans_path
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    @user.photo.attach(params[:photo])
    if @user.save
        flash[:notice] = "Welcome to Edx Wallet"
        redirect_to user_path(@user)
    else
        render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="booking-container">
  <h1>My bookings</h1>
  <div class="bookings">
    <% @bookings.each do |booking| %>
      <div class="booking-box">
        <%= link_to booking_path(booking), class: "img-container" do %>
          <% booking.caravan.photos.each do |photo| %>
            <div class="img-of-caravan" style="background-image: url('<%= cl_image_path photo.key, crop: :fill%>')">
            </div>
          <% end %>
        <% end %>
        <div class="content-box">
          <div>
            <%= link_to booking_path(booking), {:style=>'text-decoration:none; color: black;'} do %>
              <h3> <%= booking.caravan.model%> from <%= booking.user.username.capitalize %></h3>
            <% end %>
            <h6><i class="fa-solid fa-location-dot"></i> <%= booking.caravan.location %></h6>
            <h5>From: <%= booking.start_date.strftime("%A, %b %d") %></h5>
            <h5>To: <%= booking.end_date.strftime("%A, %b %d") %></h5>
            <h5>$ <%= (booking.caravan.price).to_i %> × <%= (booking.end_date - booking.start_date).to_i %> <%= (booking.end_date - booking.start_date).to_i > 1 ? "nights" : "night"  %> </h5>
            <h5 id="total-price">Total: $ <%= (booking.caravan.price * (booking.end_date - booking.start_date)).to_i %></h5>
            <h6>Cancellation policy: <a class="cancel" href="#">Moderate</a></h6>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="bookings-show">
  <div class="model-date">
    <h1><%= @booking.caravan.model %></h1>
    <h1><%= @booking.start_date.strftime("%A, %b %d") %> - <%= @booking.end_date.strftime("%A, %b %d") %></h1>
  </div>
  <div class="d-flex justify-content-between">
    <div>
      <p>Location: <%= @booking.caravan.location %></p>
    </div>
    <div>
      <p>Year: <%= @booking.caravan.year.nil? ? "N/A" : @booking.caravan.year %> </p>
    </div>
    <div>
      <p>Fuel type: <%= @booking.caravan.fuelType.nil? ? "N/A" : @booking.caravan.fuelType.capitalize %></p>
    </div>
    <div>
      <p><i class="fa-solid fa-user"></i> <%= @booking.caravan.capacity %></p>
    </div>
    <div>
      <p>Owner: <%= @booking.caravan.user.username  %></p>
    </div>
  </div>
  <div class="container-image-text">
    <div class="show-images-container-bookings">
      <% if @booking.caravan.photos.attached? %>
        <% @booking.caravan.photos.each do |photo| %>
          <div class="photo-img-booking" style="background-image: url('<%= cl_image_path photo.key, width: 560, height: 320, gravity: "auto", crop: :fill%>')">
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="description-icon">
      <div>
        <p><%= @booking.caravan.description %>
        </div>
        <div>
          <%= render "components/avatar_user" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/caravans/_info_window.html.erb
<h4><%= caravan.model %></h4>
<h5>from <%= caravan.user.username.capitalize %></h5>
<h6>Capacity: <%= caravan.capacity%> <%= caravan.capacity > 1 ? "people" : "person" %></h6>
<h6 class="last-h6">Price: $<%= caravan.price.to_i %> per day</h6>
<%= link_to "Book now", caravan_path(caravan), class: "book-btn" %>

app/views/caravans/edit.html.erb
<div class="container" id="simple-form-new">
<%= link_to "Back", caravan_path, class: "btn btn-primary back-btn" %>
<h1 id="header-simple-form">Update listing</h1>
<%# <%= simple_form_for(@caravan) do |f| %>
  <%# <%= f.submit "Submit picture", class: "btn btn-primary" %>
  <%# <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%# <%= f.input :location, %>
  <%# input_html: {data: {location_autocomplete_target: "location"}}, %>
  <%# wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
<%# <% end %>



 <%= simple_form_for(@caravan) do |f| %>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.input :model %>
    </div>
    <div class="form-group col-md-6">
      <%= f.input :price %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.input :location,
        input_html: {data: {location_autocomplete_target: "location"}},
        wrapper_html: {data: {controller: "location-autocomplete", location_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}} %>
    </div>
    <div class="form-group col-md-6">
      <%= f.input :capacity %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.input :year %>
    </div>
    <div class="form-group col-md-6">
      <%= f.input :fuelType, prompt: 'Select a Fuel Type', collection: Caravan::FUEL_TYPES %>
    </div>
  </div>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :description, as: :text, input_html: {rows: 3}  %>
    <%= f.submit class:"btn submit-btn"%>
  <% end %>
</div>

app/views/caravans/index.html.erb
<div class="caravans-index">
  <%# <div class="bar">
    <h1>Current listing:</h1>
    <%= link_to "Add a listing", new_caravan_path, type: "button", class: "btn btn-dark"%>
  <%# </div> %>
  <div style="width: 100%; height: 600px;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="listings">
    <% @caravans.each do |caravan| %>
      <div class="listing">
        <div class="image-container">
          <% if caravan.photos.attached? %>
            <%= link_to caravan_path(caravan) do %>
              <% caravan.photos.each do |photo| %>
                <div class="photo-img" style="background-image: url('<%= cl_image_path photo.key, crop: :fill %>')"></div>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <div class="description">
          <div class="naming">
            <h4><%= link_to caravan.model, caravan_path(caravan), class: "a" %></h4>
            <p><%= caravan.location %></p>
          </div>
          <div class="right">
            <h5>€ <%= caravan.price.to_i %></h5>
            <p><i class="fa-solid fa-user"></i> <%= caravan.capacity %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/caravans/new.html.erb
<div class="container" id="simple-form-new">
<h1 id="header-simple-form">Create a Listing</h1>
<br>
  <%= simple_form_for(@caravan) do |f| %>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.input :location %>
    </div>
    <div class="form-group col-md-6">
      <%= f.input :price %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.input :model %>
    </div>
    <div class="form-group col-md-6">
      <%= f.input :capacity %>
    </div>
  </div>
  <div class="row">
    <div class="form-group col-md-6">
      <%= f.input :year %>
    </div>
    <div class="form-group col-md-6">
      <%= f.input :fuelType, prompt: 'Select a Fuel Type', collection: Caravan::FUEL_TYPES %>
    </div>
  </div>
    <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <%= f.input :description, as: :text, input_html: {rows: 3}  %>
    <%= f.submit class:"btn submit-btn"%>
  <% end %>
</div>

app/views/caravans/show.html.erb
<div class="caravans-show">
  <div class="head">
    <h1><%= @caravan.model %></h1>
    <div class="btn edit-btn"><%= link_to "Edit listing", edit_caravan_path, class: "edit" %></div>
  </div>
  <div class="d-flex justify-content-between">
    <div>
      <p><i class="fa-solid fa-location-dot"></i> <%= @caravan.location %></p>
    </div>
    <div>
      <p><i class="fa-solid fa-van-shuttle"></i> <%= @caravan.user.username %></p>
    </div>
  </div>
  <div class="show-images-container">
    <% if @caravan.photos.attached? %>
      <% @caravan.photos.each do |photo| %>
        <div class="photo-img" style="background-image: url('<%= cl_image_path photo.key, crop: :fill%>')"></div>
      <% end %>
    <% end %>
  </div>
  <div class="show-info-container">
    <div class="info-header d-flex justify-content-between">
      <div>
        <h3>Caravan rented out by <%= @caravan.user.username %></h3>
        <p><i class="fa-solid fa-user"></i> <%= @caravan.capacity %></p>
      </div>
      <div>
        <% if @caravan.user.photo.present? %>
          <%= cl_image_tag @caravan.user.photo.key, class: "avatar" %>
        <% else %>
          <%= image_tag "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-Vector-PNG-Cutout.png", style:"height: 60px; width: 60px; background-color: darkgrey; border-radius: 50%;" %>
        <% end %>
      </div>
    </div>
    <div class="info-body">
      <div>
        <p>Year: <%= @caravan.year.nil? ? "N/A" : @caravan.year %> </p>
        <p>Fuel type: <%= @caravan.fuelType.nil? ? "N/A" : @caravan.fuelType.capitalize %></p>
        <p> Description: <%= @caravan.description %></p>
      </div>
      <div data-controller="booking-card">
        <%= render "components/booking_card" %>
      </div>
    </div>
  </div>
</div>

app/views/caravans/user_listings.html.erb
<div class="caravans-user-listings">
  <div class="d-flex justify-content-between">
    <h1>My listings</h1>
    <h1><%= link_to new_caravan_path, class: "create-button" do %><i class="fa-solid fa-circle-plus"></i> <% end %></h1>
  </div>
  <% if @caravans.empty? %>
    <h2>You have no caravans listed</h2>
  <% else %>
    <% @caravans.each do |caravan| %>
      <div class="user-listing">
        <div class="image-container">
          <%= link_to caravan_path(caravan), class: "img-container" do %>
            <% if caravan.photos.attached? %>
              <div class="photo-img" style="background-image: url('<%= cl_image_path caravan.photos.first.key, crop: :fill%>')"></div>
            <% end %>
          <% end %>
        </div>
        <div class="content">
          <div>
            <div class="d-flex justify-content-between">
              <%= link_to caravan_path(caravan), class: "header-link" do %>
                <h2><%= caravan.model %></h2>
              <% end %>
              <h4><span id="price">€ <%= caravan.price.to_i %></span> / day </h4>
            </div>
            <div>
              <h5><i class="fa-solid fa-location-dot"></i>  <%= caravan.location %></h5>
              <h5><i class="fa-solid fa-user"></i> <%= caravan.capacity %> people</h5>
              <h5><i class="fa-solid fa-gas-pump"></i> <%= caravan.fuelType.capitalize %></h5>
              <h5><i class="fa-solid fa-clock"></i> <%= caravan.year %></h5>
            </div>
          </div>
          <div>
            <%= link_to "Edit", edit_caravan_path(caravan) , class: "btn btn-danger" %>
            <%= link_to "Delete", caravan_path(caravan) , class: "btn btn-danger", data: {"turbo-method": :delete} %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vanify</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>
  <body>
    <div class="background">
      <div class="page-container">
        <div class="navbar-container"><%= render "shared/navbar" %></div>
        <div class="content-container"><%= yield %></div>
        <%= render "shared/footer" %>
      </div>
    </div>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
    <footer class="site-footer">
      <div class="container">
          <div class="row-headers">
            <div class="all-links">
              <div class="">
                <%= "© 2022 Vanify, Inc." %>
              </div>
              <div class="footer-links">
                <%= link_to "About Us", "#"%>
              </div>
              <div class="footer-links">
                <%= link_to "Contact Us", "#"%>
              </div>
              <div class="footer-links">
                <%= link_to "Support", "#"%>
              </div>
            </div>
            <div class="icons-group">
              <a href="https://www.instagram.com/themoderncaravan/" class="fa-brands fa-instagram" target="_blank"></a>
              <a href="https://twitter.com/caravanclub" class="fa-brands fa-twitter" target="_blank"></a>
              <a href="https://www.linkedin.com/company/campervanhire" class="fa-brands fa-linkedin" target="_blank"></a>
            </div>
          </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="logo-text-nav">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
      <% end %>
      <%= link_to root_path, class: "navbar-brand" do %>
        <h3 id="logo-text">Vanify</h3>
      <% end %>
    </div>
    <div>
      <%= render "components/searchbar" %>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My bookings", bookings_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "My listings", user_listings_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.photo.present? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
            <% else %>
              <%= image_tag "https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-Vector-PNG-Cutout.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item"  %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link-button" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>